
  create table "public"."feedback" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "email" text,
    "grund" text,
    "nachricht" text
      );


alter table "public"."feedback" enable row level security;


  create table "public"."pdf_files" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "file_path" text not null,
    "date_of_absence" text not null,
    "created_at" timestamp without time zone default now(),
    "reason" text default ''::text,
    "pdf_name" text
      );


alter table "public"."pdf_files" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "first_name" text,
    "last_name" text,
    "birthday" text,
    "class" text,
    "calendar_url" text,
    "first_name_trainer" text,
    "last_name_trainer" text,
    "phone_number_trainer" text,
    "email_trainer" text,
    "onboarding_completed" boolean default false,
    "isFullNameEnabled" boolean not null default true,
    "isFullSubjectEnabled" boolean not null default true,
    "isDoNotSaveEnabled" boolean not null default false,
    "is_encrypted" boolean default false,
    "encrypted_data" text,
    "encryption_salt" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "has_pin" boolean not null default false,
    "pin_hash" text
      );


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX feedback_pkey ON public.feedback USING btree (id);

CREATE UNIQUE INDEX pdf_files_pkey ON public.pdf_files USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."feedback" add constraint "feedback_pkey" PRIMARY KEY using index "feedback_pkey";

alter table "public"."pdf_files" add constraint "pdf_files_pkey" PRIMARY KEY using index "pdf_files_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.add_generated_absence()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    INSERT INTO generated_absences (success) 
    VALUES (true);  -- Ersetzen Sie NEW.column1 und NEW.column2 durch die tatsächlichen Spaltennamen
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.count_generated_absences()
 RETURNS bigint
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN (SELECT COUNT(*) FROM public.generated_absences);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$begin 
    insert into public.profiles (id) 
    values (new.id);   
    
    return new; 
end;$function$
;

CREATE OR REPLACE FUNCTION public.insert_generated_absence()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    INSERT INTO public.generated_absences (success) 
    VALUES (true);
    
    RETURN NEW;
END;
$function$
;

grant delete on table "public"."feedback" to "anon";

grant insert on table "public"."feedback" to "anon";

grant references on table "public"."feedback" to "anon";

grant select on table "public"."feedback" to "anon";

grant trigger on table "public"."feedback" to "anon";

grant truncate on table "public"."feedback" to "anon";

grant update on table "public"."feedback" to "anon";

grant delete on table "public"."feedback" to "authenticated";

grant insert on table "public"."feedback" to "authenticated";

grant references on table "public"."feedback" to "authenticated";

grant select on table "public"."feedback" to "authenticated";

grant trigger on table "public"."feedback" to "authenticated";

grant truncate on table "public"."feedback" to "authenticated";

grant update on table "public"."feedback" to "authenticated";

grant delete on table "public"."feedback" to "service_role";

grant insert on table "public"."feedback" to "service_role";

grant references on table "public"."feedback" to "service_role";

grant select on table "public"."feedback" to "service_role";

grant trigger on table "public"."feedback" to "service_role";

grant truncate on table "public"."feedback" to "service_role";

grant update on table "public"."feedback" to "service_role";

grant delete on table "public"."pdf_files" to "anon";

grant insert on table "public"."pdf_files" to "anon";

grant references on table "public"."pdf_files" to "anon";

grant select on table "public"."pdf_files" to "anon";

grant trigger on table "public"."pdf_files" to "anon";

grant truncate on table "public"."pdf_files" to "anon";

grant update on table "public"."pdf_files" to "anon";

grant delete on table "public"."pdf_files" to "authenticated";

grant insert on table "public"."pdf_files" to "authenticated";

grant references on table "public"."pdf_files" to "authenticated";

grant select on table "public"."pdf_files" to "authenticated";

grant trigger on table "public"."pdf_files" to "authenticated";

grant truncate on table "public"."pdf_files" to "authenticated";

grant update on table "public"."pdf_files" to "authenticated";

grant delete on table "public"."pdf_files" to "service_role";

grant insert on table "public"."pdf_files" to "service_role";

grant references on table "public"."pdf_files" to "service_role";

grant select on table "public"."pdf_files" to "service_role";

grant trigger on table "public"."pdf_files" to "service_role";

grant truncate on table "public"."pdf_files" to "service_role";

grant update on table "public"."pdf_files" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "Allow everyone to insert feedback"
  on "public"."feedback"
  as permissive
  for insert
  to authenticated, anon
with check (true);



  create policy "Enable insert for users based on user_id"
  on "public"."pdf_files"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to delete their own data only"
  on "public"."pdf_files"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."pdf_files"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable insert for users based on user_id"
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable users to view their own data only"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = id));



  create policy "Nur eigenes Profil bearbeiten!"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) = id))
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Nur eigenes Profil erstellen!"
  on "public"."profiles"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Users can insert their own profile"
  on "public"."profiles"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Users can update their own profile"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) = id))
with check ((( SELECT auth.uid() AS uid) = id));


CREATE TRIGGER pdf_files_insert_trigger AFTER INSERT ON public.pdf_files FOR EACH ROW EXECUTE FUNCTION public.add_generated_absence();
ALTER TABLE "public"."pdf_files" DISABLE TRIGGER "pdf_files_insert_trigger";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER "send-welcome-email" AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://uvvchmphtkqsfpaydagn.supabase.co/functions/v1/send-welcome-email', 'POST', '{"Content-type":"application/json"}', '{}', '5000');

CREATE TRIGGER sf AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://uvvchmphtkqsfpaydagn.supabase.co/functions/v1/addContact', 'POST', '{"Content-type":"application/json"}', '{"email":"payload.new.Email"}', '5000');


  create policy "Give users access to own folder 1nzuh98_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'pdf-files'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give users access to own folder 1nzuh98_1"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'pdf-files'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give users access to own folder 1nzuh98_2"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (((bucket_id = 'pdf-files'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



